language: php
sudo: false

php:
  - "7.1"
  - "7.2"
  - "7.3"

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --prefer-dist --no-interaction

script:
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; else vendor/bin/phpunit; fi
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then vendor/bin/php-cs-fixer fix --config=vendor/ixocreate/coding-standard/.php_cs -v --dry-run --using-cache=no --path-mode=intersection `git diff --name-only --diff-filter=ACMRTUXB $TRAVIS_COMMIT_RANGE`; fi

after_success:
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then php vendor/bin/php-coveralls -v; fi

notifications:
  email: false
  slack:
    secure: "XTyqUp/NoUR79H0X9lPaukc5EO5Ud07fIpo5Flk251bdUNZ7J/+IqCuZGbVk4ELWDKwXj+ssFGYJ8yniQNXJO3xLsX95UvYISMjk02D7NB85sP024UsxHoS1/+WLcAMxHSfJPsZomPZNzUQPTJGQAXuv7/tPiNVpxK65lGCTZJsA6uzKIZBM4YVYx+rMRts1mDdoamQzwvUWLLtwoqty72u5oc7yI4HF/Wa5OO/R33l4wevZpEMj6Ng+Xb7VX9aDPG7/sC5H+JVGdD+qAM3XmIJHB/VQfYohb4j+LxmCM2iqmHK7v1qzf+MffHaaI1FBGFMLo6cNj8KUZ7gil4yU1nRZFDep436m1l+s+xYhHBi7CBnwMDSr7aJDgW1S/G7ugERn0c4Po+03I+m69t7R9qwk5BiCRP5OrfKrVQCCCuE4dspMO+k2rsk9gBlMN6eOZswgGoLP+IY8YO8KmpglMA18yIpR+sFkfFpSXc/MTlzuwCAemyTtr0kDikkBOMltMLejVHPOV4noxawj0C/8xZs9ujoht7QRD5EXrsV9cJak55sPW2IK/Bzkp+tchTIiiBXj8Ppkk+91VxKpfHXW3KyNB+9TRRAnAQNe0d2wzFAkJoHxw1LdPPhguLJuoscW2JPWSb9tO1C7Q/rO74dAP/9jiOHCM+dMOss1VsibC50="
